In [1]:
import os

print(os.path.abspath(os.curdir))

e:\Data Kuliah\S2 ITS\Semester 5\Sentiment Analysis\IEEE IFS\DroneLog\notebooks

In [2]:
import os
os.chdir("..")

In [3]:
print(os.path.abspath(os.curdir))

e:\Data Kuliah\S2 ITS\Semester 5\Sentiment Analysis\IEEE IFS\DroneLog

# Ablation Study
This ablation study is based on the chi-square test results. Only significant hyperparameters toward the accuracy are analyzed.

In [27]:
import pandas as pd

baseline_path = 'experiments/recap/final-recap-all.xlsx'
baseline_df = pd.read_excel(baseline_path)
baseline_df.head(5)

,dataset,encoder,n_layer,n_head,bidirectional,pooling,class_weight,scenario,best_epoch,accuracy,precision,recall,f1_score
0,filtered,gru,1,1,bidirectional,mean,balanced,cross_entropy,8,77.77778,77.93382,77.77778,77.31932
1,filtered,gru,1,1,unidirectional,mean,balanced,cross_entropy,8,76.92308,76.20133,76.92308,76.50683
2,filtered,gru,2,1,bidirectional,mean,balanced,cross_entropy,7,77.77778,78.38493,77.77778,77.55844
3,filtered,gru,2,1,unidirectional,mean,balanced,cross_entropy,10,77.77778,77.50018,77.77778,77.55259
4,filtered,gru,3,1,bidirectional,mean,balanced,cross_entropy,10,76.06838,75.01045,76.06838,74.54848

In [28]:
# Group by 'dataset', 'encoder', and 'scenario', and calculate mean and std
grouped = baseline_df.groupby(['dataset', 'encoder', 'scenario'])['accuracy'].agg(['mean', 'std'])
grouped

                                           mean       std
dataset    encoder     scenario
filtered   gru         cross_entropy  77.825263  1.153136
                       focal          77.492878  2.134238
                       multitask-101  78.300096  1.857322
                       multitask-111  78.347579  2.670813
           linear      cross_entropy  78.133905  1.385771
                       focal          78.917380  1.226906
                       multitask-101  77.706554  1.802379
                       multitask-111  77.065530  1.253678
           lstm        cross_entropy  79.297247  1.038777
                       focal          78.679963  1.887917
                       multitask-101  76.305794  4.123101
                       multitask-111  75.735993  6.749934
           transformer cross_entropy  78.672049  1.324014
                       focal          78.387149  1.352919
                       multitask-101  78.395063  1.732542
                       multitask-111  77.769866  1.907576
unfiltered gru         cross_entropy  94.928075  0.396392
                       focal          94.791667  0.612495
                       multitask-101  94.828870  0.473509
                       multitask-111  95.002480  0.552833
           linear      cross_entropy  95.070684  0.489576
                       focal          95.145089  0.393871
                       multitask-101  94.717263  0.384662
                       multitask-111  94.735864  0.648742
           lstm        cross_entropy  94.766866  0.384508
                       focal          94.841271  0.626165
                       multitask-101  94.704862  0.489072
                       multitask-111  94.568452  0.921927
           transformer cross_entropy  95.010748  0.445713
                       focal          94.812335  0.404708
                       multitask-101  94.826802  0.566692
                       multitask-111  94.878472  0.647967

In [29]:
# Pivot the grouped data to create the desired format
pivot_table = grouped.reset_index().pivot(index=['dataset', 'scenario'], columns='encoder', values=['mean', 'std'])
print(pivot_table.columns)
# Flatten the column names in the resulting DataFrame
pivot_table.columns = ['{}_{}'.format(col[0], col[1]) for col in pivot_table.columns]

# Reset the index to make 'dataset' and 'scenario' regular columns
final_df = pivot_table.reset_index()

# Rename columns as needed
final_df.rename(columns={'dataset': 'Dataset', 'scenario': 'Scenario'}, inplace=True)

# Display the final DataFrame
# final_df.to_excel
root_workdir = os.path.join('experiments', 'recap', 'hyperparam')
if not os.path.exists(root_workdir):
    os.makedirs(root_workdir)
final_df.to_excel(os.path.join('experiments', 'recap', 'hyperparam', 'recap_per_scenario.xlsx'), index=False, float_format='%.3f')
print(final_df)

MultiIndex([('mean',         'gru'),
            ('mean',      'linear'),
            ('mean',        'lstm'),
            ('mean', 'transformer'),
            ( 'std',         'gru'),
            ( 'std',      'linear'),
            ( 'std',        'lstm'),
            ( 'std', 'transformer')],
           names=[None, 'encoder'])
      Dataset       Scenario   mean_gru  mean_linear  mean_lstm  \
0    filtered  cross_entropy  77.825263    78.133905  79.297247
1    filtered          focal  77.492878    78.917380  78.679963
2    filtered  multitask-101  78.300096    77.706554  76.305794
3    filtered  multitask-111  78.347579    77.065530  75.735993
4  unfiltered  cross_entropy  94.928075    95.070684  94.766866
5  unfiltered          focal  94.791667    95.145089  94.841271
6  unfiltered  multitask-101  94.828870    94.717263  94.704862
7  unfiltered  multitask-111  95.002480    94.735864  94.568452

   mean_transformer   std_gru  std_linear  std_lstm  std_transformer
0         78.672049  1.153136    1.385771  1.038777         1.324014
1         78.387149  2.134238    1.226906  1.887917         1.352919
2         78.395063  1.857322    1.802379  4.123101         1.732542
3         77.769866  2.670813    1.253678  6.749934         1.907576
4         95.010748  0.396392    0.489576  0.384508         0.445713
5         94.812335  0.612495    0.393871  0.626165         0.404708
6         94.826802  0.473509    0.384662  0.489072         0.566692
7         94.878472  0.552833    0.648742  0.921927         0.647967

## 1. Filtered Dataset

In [30]:
filtered_df = baseline_df[baseline_df['dataset'] == 'filtered']
filtered_df

,dataset,encoder,n_layer,n_head,bidirectional,pooling,class_weight,scenario,best_epoch,accuracy,precision,recall,f1_score
0,filtered,gru,1,1,bidirectional,mean,balanced,cross_entropy,8,77.77778,77.93382,77.77778,77.31932
1,filtered,gru,1,1,unidirectional,mean,balanced,cross_entropy,8,76.92308,76.20133,76.92308,76.50683
2,filtered,gru,2,1,bidirectional,mean,balanced,cross_entropy,7,77.77778,78.38493,77.77778,77.55844
3,filtered,gru,2,1,unidirectional,mean,balanced,cross_entropy,10,77.77778,77.50018,77.77778,77.55259
4,filtered,gru,3,1,bidirectional,mean,balanced,cross_entropy,10,76.06838,75.01045,76.06838,74.54848
...,...,...,...,...,...,...,...,...,...,...,...,...,...
931,filtered,transformer,3,4,unidirectional,min,uniform,multitask-111,7,80.34188,80.28228,80.34188,79.72798
932,filtered,transformer,3,6,unidirectional,min,uniform,multitask-101,8,76.92308,76.54864,76.92308,76.51554
933,filtered,transformer,3,6,unidirectional,min,uniform,multitask-111,7,79.48718,78.88667,79.48718,78.91946
934,filtered,transformer,3,8,unidirectional,min,uniform,multitask-101,5,79.48718,79.14762,79.48718,78.81173
935,filtered,transformer,3,8,unidirectional,min,uniform,multitask-111,10,79.48718,79.68513,79.48718,79.04302

### A. F-GRU (scenario-class weight)

In [31]:
# Group by 'dataset', 'encoder', and 'scenario', and calculate mean and std
filtered_gru = filtered_df[filtered_df['encoder'] == 'gru']
grouped_f_gru = filtered_gru.groupby(['class_weight', 'scenario'])['accuracy'].agg(['mean', 'std'])
grouped_f_gru.to_excel(os.path.join('experiments', 'recap', 'hyperparam', 'recap_f_gru_scenario_class-weight.xlsx'), index=True, float_format='%.3f')
grouped_f_gru

                                 mean       std
class_weight scenario
balanced     cross_entropy  77.635330  1.136033
             focal          76.780627  2.190217
             multitask-101  79.344730  1.258084
             multitask-111  78.632480  2.356245
inverse      cross_entropy  77.635330  1.136033
             focal          76.780627  2.559351
             multitask-101  76.495728  1.772347
             multitask-111  76.353278  2.629739
uniform      cross_entropy  78.205130  1.296217
             focal          78.917380  0.697860
             multitask-101  79.059830  1.046789
             multitask-111  80.056980  1.846363

### B. F-LSTM (scenario-bidirectionality)

In [32]:
# Group by 'dataset', 'encoder', and 'scenario', and calculate mean and std
filtered_lstm = filtered_df[filtered_df['encoder'] == 'lstm']
grouped_f_lstm = filtered_lstm.groupby(['bidirectional', 'scenario'])['accuracy'].agg(['mean', 'std'])
grouped_f_lstm.to_excel(os.path.join('experiments', 'recap', 'hyperparam', 'recap_f_lstm_scenario_bidirectionality.xlsx'), index=True, float_format='%.3f')
grouped_f_lstm

                                   mean       std
bidirectional  scenario
bidirectional  cross_entropy  79.487180  1.282050
               focal          79.392213  2.318918
               multitask-101  77.302946  2.305758
               multitask-111  75.973410  4.805449
unidirectional cross_entropy  79.107313  0.753775
               focal          77.967713  1.027222
               multitask-101  75.308643  5.345204
               multitask-111  75.498576  8.579001

### C. F-Linear (scenario-class weight)

In [33]:
# Group by 'dataset', 'encoder', and 'scenario', and calculate mean and std
filtered_linear = filtered_df[filtered_df['encoder'] == 'linear']
grouped_f_linear = filtered_linear.groupby(['class_weight', 'scenario'])['accuracy'].agg(['mean', 'std'])
grouped_f_linear.to_excel(os.path.join('experiments', 'recap', 'hyperparam', 'recap_f_linear_scenario_class-weight.xlsx'), index=True, float_format='%.3f')
grouped_f_linear

                                 mean       std
class_weight scenario
balanced     cross_entropy  77.991455  1.762009
             focal          78.632480  1.208728
             multitask-101  78.418805  1.617921
             multitask-111  77.136755  1.282050
inverse      cross_entropy  77.991455  1.762009
             focal          79.700855  1.459678
             multitask-101  76.709402  2.353664
             multitask-111  75.854705  0.427350
uniform      cross_entropy  78.418805  0.818313
             focal          78.418805  0.818313
             multitask-101  77.991455  1.282050
             multitask-111  78.205130  0.493461

### D. F-Transformer (scenario-class weight)

In [34]:
# Group by 'dataset', 'encoder', and 'scenario', and calculate mean and std
filtered_transformer = filtered_df[filtered_df['encoder'] == 'transformer']
grouped_f_trans_class = filtered_transformer.groupby(['class_weight', 'scenario'])['accuracy'].agg(['mean', 'std'])
grouped_f_trans_class.to_excel(os.path.join('experiments', 'recap', 'hyperparam', 'recap_f_trans_scenario_class-weight.xlsx'), index=True, float_format='%.3f')
grouped_f_trans_class

                                 mean       std
class_weight scenario
balanced     cross_entropy  78.466288  1.256470
             focal          77.825263  1.080046
             multitask-101  78.893638  1.321246
             multitask-111  78.086422  1.571384
inverse      cross_entropy  78.466288  1.256470
             focal          78.038938  1.427549
             multitask-101  77.089271  1.367818
             multitask-111  76.187087  1.342146
uniform      cross_entropy  79.083572  1.393017
             focal          79.297247  1.044016
             multitask-101  79.202280  1.697146
             multitask-111  79.036088  1.588995

### E. F-Transformer (scenario - n_layer)

In [35]:
# Group by 'dataset', 'encoder', and 'scenario', and calculate mean and std
filtered_transformer = filtered_df[filtered_df['encoder'] == 'transformer']
grouped_f_trans_nlayer = filtered_transformer.groupby(['n_layer', 'scenario'])['accuracy'].agg(['mean', 'std'])
grouped_f_trans_nlayer.to_excel(os.path.join('experiments', 'recap', 'hyperparam', 'recap_f_trans_scenario_n-layer.xlsx'), index=True, float_format='%.3f')
grouped_f_trans_nlayer

                            mean       std
n_layer scenario
1       cross_entropy  77.872747  1.272290
        focal          77.754038  1.146448
        multitask-101  77.421654  1.773816
        multitask-111  76.780629  1.911169
2       cross_entropy  78.727447  1.239046
        focal          79.036088  1.234123
        multitask-101  79.463438  1.535555
        multitask-111  78.418805  1.298228
3       cross_entropy  79.415955  0.987803
        focal          78.371322  1.382992
        multitask-101  78.300097  1.230595
        multitask-111  78.110163  2.056136

### F. F-Transformer (scenario-n_layer)

In [36]:
# Group by 'dataset', 'encoder', and 'scenario', and calculate mean and std
filtered_transformer = filtered_df[filtered_df['encoder'] == 'transformer']
grouped_f_trans_layer = filtered_transformer.groupby(['n_layer', 'scenario'])['accuracy'].agg(['mean', 'std'])
grouped_f_trans_layer.to_excel(os.path.join('experiments', 'recap', 'hyperparam', 'recap_f_trans_scenario_n-layer.xlsx'), index=True, float_format='%.3f')
grouped_f_trans_layer

                            mean       std
n_layer scenario
1       cross_entropy  77.872747  1.272290
        focal          77.754038  1.146448
        multitask-101  77.421654  1.773816
        multitask-111  76.780629  1.911169
2       cross_entropy  78.727447  1.239046
        focal          79.036088  1.234123
        multitask-101  79.463438  1.535555
        multitask-111  78.418805  1.298228
3       cross_entropy  79.415955  0.987803
        focal          78.371322  1.382992
        multitask-101  78.300097  1.230595
        multitask-111  78.110163  2.056136

## 2. Unfiltered Dataset

In [37]:
unfiltered_df = baseline_df[baseline_df['dataset'] == 'unfiltered']
unfiltered_df

,dataset,encoder,n_layer,n_head,bidirectional,pooling,class_weight,scenario,best_epoch,accuracy,precision,recall,f1_score
312,unfiltered,gru,1,1,bidirectional,mean,balanced,cross_entropy,3,94.41964,94.58389,94.41964,94.33795
313,unfiltered,gru,1,1,unidirectional,mean,balanced,cross_entropy,5,95.53571,95.75676,95.53571,95.62940
314,unfiltered,gru,2,1,bidirectional,mean,balanced,cross_entropy,8,94.41964,94.15089,94.41964,94.19360
315,unfiltered,gru,2,1,unidirectional,mean,balanced,cross_entropy,4,94.64286,94.72368,94.64286,94.59757
316,unfiltered,gru,3,1,bidirectional,mean,balanced,cross_entropy,4,95.31250,95.66057,95.31250,95.44276
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1243,unfiltered,transformer,3,4,unidirectional,min,uniform,multitask-111,3,95.98214,95.95250,95.98214,95.93091
1244,unfiltered,transformer,3,6,unidirectional,min,uniform,multitask-101,7,95.53571,94.82718,95.53571,94.92682
1245,unfiltered,transformer,3,6,unidirectional,min,uniform,multitask-111,9,95.75893,96.15029,95.75893,95.89511
1246,unfiltered,transformer,3,8,unidirectional,min,uniform,multitask-101,3,94.64286,94.75057,94.64286,94.56720
1247,unfiltered,transformer,3,8,unidirectional,min,uniform,multitask-111,9,95.08929,95.08189,95.08929,95.06722

### A. U-GRU (scenario - n_layer)

In [38]:
# Group by 'dataset', 'encoder', and 'scenario', and calculate mean and std
unfiltered_gru = unfiltered_df[unfiltered_df['encoder'] == 'gru']
grouped_u_gru_nlayer = unfiltered_gru.groupby(['n_layer', 'scenario'])['accuracy'].agg(['mean', 'std'])
grouped_u_gru_nlayer.to_excel(os.path.join('experiments', 'recap', 'hyperparam', 'recap_u_gru_scenario_n-layer.xlsx'), index=True, float_format='%.3f')
grouped_u_gru_nlayer

                            mean       std
n_layer scenario
1       cross_entropy  95.014880  0.502439
        focal          94.940478  0.270326
        multitask-101  94.791667  0.521894
        multitask-111  94.866072  0.582074
2       cross_entropy  94.642857  0.199650
        focal          94.233630  0.384464
        multitask-101  94.680062  0.357609
        multitask-111  94.791665  0.540653
3       cross_entropy  95.126488  0.296687
        focal          95.200892  0.673353
        multitask-101  95.014882  0.540651
        multitask-111  95.349703  0.433211

### A-2. U-GRU (scenario - class weight)

In [39]:
# Group by 'dataset', 'encoder', and 'scenario', and calculate mean and std
unfiltered_gru = unfiltered_df[unfiltered_df['encoder'] == 'gru']
grouped_u_gru_class = unfiltered_gru.groupby(['class_weight', 'scenario'])['accuracy'].agg(['mean', 'std'])
grouped_u_gru_class.to_excel(os.path.join('experiments', 'recap', 'hyperparam', 'recap_u_gru_scenario_class-weight.xlsx'), index=True, float_format='%.3f')
grouped_u_gru_class

                                 mean       std
class_weight scenario
balanced     cross_entropy  94.940475  0.502439
             focal          94.456847  0.572001
             multitask-101  94.717263  0.304972
             multitask-111  94.940477  0.576339
inverse      cross_entropy  94.940475  0.502439
             focal          94.903273  0.765682
             multitask-101  94.791668  0.626062
             multitask-111  94.680060  0.477006
uniform      cross_entropy  94.903275  0.168031
             focal          95.014880  0.390891
             multitask-101  94.977678  0.483915
             multitask-111  95.386903  0.415603

### B. U-LSTM (scenario - n_layer)

In [40]:
# Group by 'dataset', 'encoder', and 'scenario', and calculate mean and std
unfiltered_lstm = unfiltered_df[unfiltered_df['encoder'] == 'lstm']
grouped_u_lstm_nlayer = unfiltered_lstm.groupby(['n_layer', 'scenario'])['accuracy'].agg(['mean', 'std'])
grouped_u_lstm_nlayer.to_excel(os.path.join('experiments', 'recap', 'hyperparam', 'recap_u_lstm_scenario_n-layer.xlsx'), index=True, float_format='%.3f')
grouped_u_lstm_nlayer

                            mean       std
n_layer scenario
1       cross_entropy  94.642857  0.598949
        focal          95.052087  0.091129
        multitask-101  94.642858  0.546760
        multitask-111  94.717260  0.715215
2       cross_entropy  94.754465  0.122257
        focal          94.828868  0.554301
        multitask-101  94.828870  0.477004
        multitask-111  94.419643  1.197896
3       cross_entropy  94.903277  0.296687
        focal          94.642858  0.957480
        multitask-101  94.642858  0.509009
        multitask-111  94.568453  0.943502

### C. U-Linear (scenario - pooling)

In [41]:
# Group by 'dataset', 'encoder', and 'scenario', and calculate mean and std
unfiltered_linear = unfiltered_df[unfiltered_df['encoder'] == 'linear']
grouped_u_linear_pooling = unfiltered_linear.groupby(['pooling', 'scenario'])['accuracy'].agg(['mean', 'std'])
grouped_u_linear_pooling.to_excel(os.path.join('experiments', 'recap', 'hyperparam', 'recap_u_linear_scenario_pooling.xlsx'), index=True, float_format='%.3f')
grouped_u_linear_pooling

                            mean       std
pooling scenario
cls     cross_entropy  94.494050  0.515493
        focal          95.089287  0.386617
        multitask-101  94.419643  0.590569
        multitask-111  95.014883  0.340964
max     cross_entropy  95.535710  0.000000
        focal          95.014880  0.464654
        multitask-101  94.791667  0.340969
        multitask-111  94.494047  0.644363
mean    cross_entropy  95.089287  0.386617
        focal          95.014880  0.257746
        multitask-101  94.866073  0.223215
        multitask-111  94.717263  0.561743
min     cross_entropy  95.163690  0.257746
        focal          95.461310  0.464654
        multitask-101  94.791667  0.340969
        multitask-111  94.717263  1.123486

### D-1. U-Transformer (scenario-class weight)

In [42]:
# Group by 'dataset', 'encoder', and 'scenario', and calculate mean and std
unfiltered_transformer = unfiltered_df[unfiltered_df['encoder'] == 'transformer']
grouped_u_trans_class = unfiltered_transformer.groupby(['class_weight', 'scenario'])['accuracy'].agg(['mean', 'std'])
grouped_u_trans_class.to_excel(os.path.join('experiments', 'recap', 'hyperparam', 'recap_u_trans_scenario_class-weight.xlsx'), index=True, float_format='%.3f')
grouped_u_trans_class

                                 mean       std
class_weight scenario
balanced     cross_entropy  95.002480  0.462952
             focal          94.760666  0.386567
             multitask-101  94.940476  0.606035
             multitask-111  94.853671  0.530760
inverse      cross_entropy  95.002480  0.462952
             focal          94.667659  0.415983
             multitask-101  94.574652  0.546292
             multitask-111  94.407242  0.610586
uniform      cross_entropy  95.027282  0.422210
             focal          95.008681  0.338112
             multitask-101  94.965278  0.466526
             multitask-111  95.374503  0.383331

### D-2. U-Transformer (scenario-n_layer)

In [43]:
# Group by 'dataset', 'encoder', and 'scenario', and calculate mean and std
# filtered_transformer = unfiltered_df[unfiltered_df['encoder'] == 'transformer']
grouped_u_trans_layer = unfiltered_transformer.groupby(['n_layer', 'scenario'])['accuracy'].agg(['mean', 'std'])
grouped_u_trans_layer.to_excel(os.path.join('experiments', 'recap', 'hyperparam', 'recap_u_trans_scenario_n-layer.xlsx'), index=True, float_format='%.3f')
grouped_u_trans_layer

                            mean       std
n_layer scenario
1       cross_entropy  94.977679  0.408112
        focal          94.847471  0.453939
        multitask-101  94.692460  0.572482
        multitask-111  94.748264  0.645805
2       cross_entropy  95.120288  0.474718
        focal          94.897074  0.333874
        multitask-101  95.188492  0.386413
        multitask-111  95.151289  0.513492
3       cross_entropy  94.934276  0.442649
        focal          94.692460  0.399694
        multitask-101  94.599454  0.546292
        multitask-111  94.735863  0.698516

## 3. Three-paired Analysis

### A. F-Transformer (n_layer - class weight - scenario)

In [44]:
grouped_f_trans_3 = filtered_transformer.groupby(['n_layer', 'class_weight', 'scenario'])['accuracy'].agg(['mean', 'std'])
grouped_f_trans_3.to_excel(os.path.join('experiments', 'recap', 'hyperparam', 'recap_f_trans_scenario_class-weight_n-layer.xlsx'), index=True, float_format='%.3f')
grouped_f_trans_3

                                         mean       std
n_layer class_weight scenario
1       balanced     cross_entropy  77.706555  1.286359
                     focal          77.207980  0.758653
                     multitask-101  77.991455  0.740192
                     multitask-111  77.065530  1.887860
        inverse      cross_entropy  77.706555  1.286359
                     focal          77.207980  0.841650
                     multitask-101  75.997153  1.286362
                     multitask-111  75.284902  1.432897
        uniform      cross_entropy  78.205130  1.288509
                     focal          78.846155  0.972803
                     multitask-101  78.276355  2.108067
                     multitask-111  77.991455  1.369704
2       balanced     cross_entropy  78.347580  1.113399
                     focal          78.561255  0.995298
                     multitask-101  80.056980  1.171528
                     multitask-111  79.131055  0.769518
        inverse      cross_entropy  78.347580  1.113399
                     focal          79.059830  1.567539
                     multitask-101  77.777780  0.814924
                     multitask-111  76.994305  0.851456
        uniform      cross_entropy  79.487180  1.208728
                     focal          79.487180  0.964232
                     multitask-101  80.555555  0.825048
                     multitask-111  79.131055  0.851456
3       balanced     cross_entropy  79.344730  0.801227
                     focal          77.706555  1.059924
                     multitask-101  78.632480  1.093336
                     multitask-111  78.062680  1.171528
        inverse      cross_entropy  79.344730  0.801227
                     focal          77.849005  1.178592
                     multitask-101  77.492880  1.279890
                     multitask-111  76.282054  1.159659
        uniform      cross_entropy  79.558405  1.336990
                     focal          79.558405  1.120830
                     multitask-101  78.774930  0.952684
                     multitask-111  79.985755  1.802378

### B. U-Transformer (n_layer - class weight - scenario)

In [45]:
grouped_u_trans_3 = unfiltered_transformer.groupby(['n_layer', 'class_weight', 'scenario'])['accuracy'].agg(['mean', 'std'])
grouped_u_trans_3.to_excel(os.path.join('experiments', 'recap', 'hyperparam', 'recap_u_trans_scenario_class-weight_n-layer.xlsx'), index=True, float_format='%.3f')
grouped_u_trans_3

                                         mean       std
n_layer class_weight scenario
1       balanced     cross_entropy  94.903274  0.434429
                     focal          94.717263  0.459758
                     multitask-101  94.996280  0.533837
                     multitask-111  94.624257  0.335949
        inverse      cross_entropy  94.903274  0.434429
                     focal          94.698661  0.447695
                     multitask-101  94.177827  0.349171
                     multitask-111  94.289433  0.682760
        uniform      cross_entropy  95.126488  0.340965
                     focal          95.126489  0.340965
                     multitask-101  94.903274  0.444734
                     multitask-111  95.331101  0.361909
2       balanced     cross_entropy  95.145090  0.504762
                     focal          94.921877  0.416236
                     multitask-101  95.405505  0.419849
                     multitask-111  95.349702  0.464656
        inverse      cross_entropy  95.145090  0.504762
                     focal          94.847470  0.335947
                     multitask-101  95.126489  0.366572
                     multitask-111  94.735863  0.374216
        uniform      cross_entropy  95.070685  0.451056
                     focal          94.921877  0.254058
                     multitask-101  95.033483  0.287511
                     multitask-111  95.368302  0.447695
3       balanced     cross_entropy  94.959077  0.451056
                     focal          94.642857  0.212828
                     multitask-101  94.419643  0.414876
                     multitask-111  94.587053  0.405209
        inverse      cross_entropy  94.959077  0.451056
                     focal          94.456845  0.390505
                     multitask-101  94.419642  0.403811
                     multitask-111  94.196429  0.631347
        uniform      cross_entropy  94.884673  0.460988
                     focal          94.977678  0.398161
                     multitask-101  94.959077  0.634625
                     multitask-111  95.424107  0.362429